files:
  include: '**/*.scss'

options:
  formatter: stylish
  merge-default-rules: false
  max-warnings: 10

rules:
  bem-depth:
    - 2
    - max-depth: 4

  border-zero:
    - 2
    - convention: '0'

  brace-style:
    - 2
    - allow-single-line: false

  class-name-format:
    - 0
    - convention: camelcase

  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: true

  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false

  extends-before-declarations: 2

  extends-before-mixins: 2

  final-newline:
    - 2
    - include: true

  force-attribute-nesting: 0

  force-element-nesting: 0

  force-pseudo-nesting: 0

  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
      ignore:
        - rem-calc

  hex-length:
    - 2
    - style: long

  hex-notation:
    - 2
    - style: lowercase

  id-name-format:
    - 1
    - convention: hyphenatedbem

  indentation:
    - 2
    - size: 2

  leading-zero:
    - 2
    - include: true

  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  mixins-before-declarations: 2

  nesting-depth:
    - 2
    - max-depth: 1

  no-color-keywords: 0

  no-color-literals: 0

  no-css-comments: 2

  no-debug: 2

  no-duplicate-properties: 2

  no-empty-rulesets: 2

  no-extends: 0

  no-ids: 1

  no-important: 1

  no-invalid-hex: 2

  no-mergeable-selectors: 0

  no-misspelled-properties:
    - 2
    - extra-properties:
       - 'overflow-scrolling'

  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-zero: 2

  no-url-protocols: 0

  no-vendor-prefixes:
    - 1
    - 'additional-identifiers': []
      'excluded-identifiers': []
      'ignore-non-standard': true

  placeholder-in-extend: 2

  placeholder-name-format:
    - 2
    - convention: hyphenatedbem

  property-sort-order:
    - 1
    - ignore-custom-properties: true
      order:
        - 'display'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'order'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'float'
        - 'clear'

        - 'transform'
        - 'transition'

        - 'animation'
        - 'animation-name'
        - 'animation-duration'
        - 'animation-timing-function'
        - 'animation-delay'
        - 'animation-iteration-count'
        - 'animation-direction'
        - 'animation-fill-mode'
        - 'animation-play-state'

        - 'visibility'
        - 'opacity'
        - 'z-index'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'outline'

        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'box-shadow'

        - 'background'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'
        - 'cursor'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'width'
        - 'min-width'
        - 'max-width'

        - 'height'
        - 'min-height'
        - 'max-height'

        - 'overflow'

        - 'list-style'
        - 'caption-side'

        - 'table-layout'
        - 'border-collapse'
        - 'border-spacing'
        - 'empty-cells'

        - 'vertical-align'

        - 'text-align'
        - 'text-indent'
        - 'text-transform'
        - 'text-decoration'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-overflow'

        - 'line-height'
        - 'word-spacing'
        - 'letter-spacing'
        - 'white-space'
        - 'color'

        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-weight'
        - 'font-smoothing'
        - 'font-style'

        - 'content'
        - 'quotes'

  property-units:
    - 2
    - global: [rem, em, '%', def, vh, vw]
      per-property:
        animation: [s, ms]
        background-position: [px, rem, em, '%', def, vh, vw]
        box-shadow: [px, rem, em]
        border: [px, rem, em]
        border-top: [px, rem, em]
        border-right: [px, rem, em]
        border-bottom: [px, rem, em]
        border-left: [px, rem, em]
        border-top-width: [px, rem, em]
        border-right-width: [px, rem, em]
        border-bottom-width: [px, rem, em]
        border-left-width: [px, rem, em]
        line-height: []
        margin: [rem, em]
        stroke-width: [px, rem, em]
        transition: [s, ms]

  quotes:
    - 2
    - style: single

  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3

  single-line-per-selector: 2

  space-after-bang:
    - 2
    - include: false

  space-after-colon:
    - 2
    - include: true

  space-after-comma: 2

  space-before-bang:
    - 2
    - include: true

  space-before-brace:
    - 2
    - include: true

  space-before-colon: 2

  space-between-parens:
    - 2
    - include: false

  trailing-semicolon: 2

  url-quotes: 2

  variable-for-property:
    - 2
    - properties:
        - font
        - z-index

  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  zero-unit: 2
